<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="CounterStrikeSharp.API" Version="1.0.355"/>
        <PackageReference Include="Dapper" Version="2.1.66"/>
        <PackageReference Include="MySqlConnector" Version="2.5.0"/>
        <Reference Include="MenuManagerApi">
            <HintPath>MenuManagerApi.dll</HintPath>
        </Reference>
    </ItemGroup>

    <ItemGroup>
        <None Update="lang\**\*.json"
              CopyToOutputDirectory="PreserveNewest"
              CopyToPublishDirectory="PreserveNewest"/>
    </ItemGroup>

</Project>
